### ISSUE TITLE
Playlist without one song

### ISSUE THREAD

**Issue by VideMelo** [skdhg/youtube-sr#51]
for some reason when i try to get a playlist it comes up without one song.

```js
const playlist = await youtube.getPlaylist(id).then((playlist) => playlist.fetch());
const videos = playlist.videos;
console.log(videos.length, playlist.videoCount); // 243 244
```

**Comment by skdhg** [comment]
What's that playlist? Could you share its id? 🤔

**Comment by VideMelo** [comment]
> What's that playlist? Could you share its id? 🤔

it's a music playlist: PLB25ZDOCzweUsuuw-jPjtA00llVZlxhuk

**Comment by skdhg** [comment]
it is possible that the video is private or is unavailable
